### ISSUE TITLE
Problem importing project

### ISSUE THREAD

**Issue by Owlman26** [KinveyApps/StatusShare-Android#1]
When I try to import the project StatusShare into eclipse I get an error stating 
"Resource '/SampleList' already exists Reason: '/SampleList' already exists"

Is there a way to fix this? Thanks

**Comment by edatkinvey** [comment]
Do you have another project named SampleList in your IDE?  If so, rename that one to SampleList1 (or something else) and try again

**Comment by edatkinvey** [comment]
closing this one out
